version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
#    expose:
#      - "8080"
#    networks:
#      - gpo
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
#    networks:
#      - gpo
  nginx:
    image: nginx
    ports:
      - "80:80"
#    expose:
#      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    networks:
#      - gpo

#networks:
#  gpo:
#    external: true