version: '3'

services:
  app:
    build: .
#    ports:
#      - "8080:8080"
    expose:
      - "8080"
    networks:
      - demo
    depends_on:
      - db
    mac_address: 02:42:ac:18:00:01
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    networks:
      - demo
    mac_address: 02:42:ac:18:00:02
  nginx:
    image: nginx
#    ports:
#      - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - demo
    depends_on:
      - app
    mac_address: 02:42:ac:18:00:03
  alembic:
    build: .
    volumes:
      - .:/app
    networks:
      - demo
    depends_on:
      - app
    entrypoint: [ "alembic" ]
    command: [ "upgrade", "head" ]

networks:
  demo:
    external: true