version: '3'

services:
  app:
    build: .
    expose:
      - "8080"
    networks:
      - gpo
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    networks:
      - gpo
  nginx:
    image: nginx
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - gpo

networks:
  gpo:
    external: true