"""add_daily_task

Revision ID: 41705203b91c
Revises: fbdc4a86694c
Create Date: 2024-11-03 09:43:30.983198

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '41705203b91c'
down_revision: Union[str, None] = 'fbdc4a86694c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Проверка, существует ли таблица daily_task
    conn = op.get_bind()
    if not conn.dialect.has_table(conn, 'daily_task'):
        op.create_table('daily_task',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('title', sa.String(), nullable=False),
            sa.Column('short_desc', sa.String(), nullable=False),
            sa.Column('destination_id', sa.Uuid(), nullable=False),
            sa.Column('number', sa.Integer(), nullable=False),
            sa.Column('day', sa.Integer(), nullable=False),
            sa.Column('is_complete', sa.Boolean(), nullable=False),
            sa.Column('is_current', sa.Boolean(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_task')
    # ### end Alembic commands ###
