"""Add closed to exercise_structure

Revision ID: 4b0fcd8d942a
Revises: 600f94ebe972
Create Date: 2025-02-22 03:42:04.803332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b0fcd8d942a'
down_revision: Union[str, None] = '600f94ebe972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_structure', sa.Column('closed', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_structure', 'closed')
    # ### end Alembic commands ###