"""Initial migration

Revision ID: 775238b67346
Revises:
Create Date: 2024-11-17 11:18:14.891217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775238b67346'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educational_theme',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_structure',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('picture_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('short_desc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('face_to_face', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('behavioral_experiment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('belief', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('difficulties', sa.String(), nullable=False),
    sa.Column('strategies', sa.String(), nullable=False),
    sa.Column('best_scenario', sa.String(), nullable=False),
    sa.Column('best_scenario_probability', sa.String(), nullable=False),
    sa.Column('worst_scenario', sa.String(), nullable=False),
    sa.Column('worst_scenario_probability', sa.String(), nullable=False),
    sa.Column('real_scenario', sa.String(), nullable=False),
    sa.Column('real_scenario_probability', sa.String(), nullable=False),
    sa.Column('alternative_belief', sa.String(), nullable=False),
    sa.Column('alternative_belief_confidence', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('psychologist_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('completed_exercise',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('exercise_structure_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_structure_id'], ['exercise_structure.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('short_desc', sa.String(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('THEORY', 'MOOD_TRACKER_AND_FREE_DIARY', 'TEST', 'OTHER', name='dailytasktype'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diary_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('situation', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('auto_thought', sa.String(), nullable=False),
    sa.Column('proofs', sa.String(), nullable=False),
    sa.Column('refutations', sa.String(), nullable=False),
    sa.Column('new_mood', sa.String(), nullable=False),
    sa.Column('alternative_thought', sa.String(), nullable=False),
    sa.Column('new_level', sa.Integer(), nullable=False),
    sa.Column('behavioral', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('psychologist_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educational_material',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('educational_theme_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['educational_theme_id'], ['educational_theme.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'SLIDER', name='fieldtype'), nullable=True),
    sa.Column('major', sa.Boolean(), nullable=False),
    sa.Column('exercise_structure_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_structure_id'], ['exercise_structure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('free_diary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiry_to_book',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'inquiry_id')
    )
    op.create_table('job_application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('psychologist_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('psychologist_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_in_feed',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('like_score', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scale',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('min', sa.Integer(), nullable=False),
    sa.Column('max', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('test_title', sa.String(), nullable=True),
    sa.Column('test_id', sa.Uuid(), nullable=True),
    sa.Column('psychologist_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('exp_date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_inquiries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'user_id', 'inquiry_id')
    )
    op.create_table('answer_choice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('borders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('left_border', sa.Float(), nullable=False),
    sa.Column('right_border', sa.Float(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_recommendation', sa.String(), nullable=True),
    sa.Column('scale_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scale_id'], ['scale.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deep_conviction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('disadaptive', sa.String(), nullable=False),
    sa.Column('adaptive', sa.String(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educational_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('educational_material_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['educational_material_id'], ['educational_material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filled_field',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('completed_exercise_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['completed_exercise_id'], ['completed_exercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ladder_of_fear_rung',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post_in_feed.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_r_i_dialog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_rational', sa.Boolean(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mood_tracker',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('free_diary_id', sa.Uuid(), nullable=True),
    sa.Column('think_diary_id', sa.Uuid(), nullable=True),
    sa.Column('diary_type', sa.Enum('FREE', 'THOUGHTS', name='diarytype'), nullable=True),
    sa.ForeignKeyConstraint(['free_diary_id'], ['free_diary.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['think_diary_id'], ['diary_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_point',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('term', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_experiment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('behavioral_experiment_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('emotion_before', sa.String(), nullable=False),
    sa.Column('emotion_level_before', sa.Integer(), nullable=False),
    sa.Column('emotion_after', sa.String(), nullable=False),
    sa.Column('emotion_level_after', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['behavioral_experiment_id'], ['behavioral_experiment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scale_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('scale_id', sa.Uuid(), nullable=False),
    sa.Column('test_result_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scale_id'], ['scale.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intermediate_belief',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('truthfulness', sa.String(), nullable=True),
    sa.Column('consistency', sa.String(), nullable=True),
    sa.Column('usefulness', sa.String(), nullable=True),
    sa.Column('feelings_and_actions', sa.String(), nullable=True),
    sa.Column('motivation', sa.String(), nullable=True),
    sa.Column('hindrances', sa.String(), nullable=True),
    sa.Column('incorrect_victims', sa.String(), nullable=True),
    sa.Column('results', sa.String(), nullable=True),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('deep_conviction', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deep_conviction'], ['deep_conviction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type'], ['type_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trouble',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_point_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plan_point_id'], ['plan_point.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trouble')
    op.drop_table('intermediate_belief')
    op.drop_table('scale_result')
    op.drop_table('result_experiment')
    op.drop_table('plan_point')
    op.drop_table('mood_tracker')
    op.drop_table('message_r_i_dialog')
    op.drop_table('like')
    op.drop_table('ladder_of_fear_rung')
    op.drop_table('filled_field')
    op.drop_table('educational_progress')
    op.drop_table('deep_conviction')
    op.drop_table('borders')
    op.drop_table('answer_choice')
    op.drop_table('user_inquiries')
    op.drop_table('token')
    op.drop_table('test_result')
    op.drop_table('task')
    op.drop_table('scale')
    op.drop_table('record')
    op.drop_table('question')
    op.drop_table('problem')
    op.drop_table('post_in_feed')
    op.drop_table('message')
    op.drop_table('job_application')
    op.drop_table('inquiry_to_book')
    op.drop_table('free_diary')
    op.drop_table('field')
    op.drop_table('educational_material')
    op.drop_table('education')
    op.drop_table('diary_record')
    op.drop_table('daily_task')
    op.drop_table('completed_exercise')
    op.drop_table('clients')
    op.drop_table('behavioral_experiment')
    op.drop_table('users')
    op.drop_table('type_analysis')
    op.drop_table('test')
    op.drop_table('review')
    op.drop_table('inquiry')
    op.drop_table('exercise_structure')
    op.drop_table('educational_theme')
    op.drop_table('book')
    # ### end Alembic commands ###
