"""review created

Revision ID: fbdc4a86694c
Revises: adfc10ebb86c
Create Date: 2024-10-14 19:51:07.121325

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fbdc4a86694c'
down_revision: Union[str, None] = 'adfc10ebb86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Проверка, существует ли таблица review
    conn = op.get_bind()
    if not conn.dialect.has_table(conn, 'review'):
        op.create_table('review',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('text', sa.String(), nullable=False),
            sa.Column('email', sa.String(), nullable=False),
            sa.Column('is_read', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
