version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
#    ports:
#    - "8080:8080"
    expose:
      - "8080"
    networks:
      - demo
    depends_on:
      - db
    mac_address: 02:42:ac:18:00:01
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    networks:
      - demo
    mac_address: 02:42:ac:18:00:02
  nginx:
    image: nginx:latest
#    ports:
#    - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - demo
    depends_on:
      - app
    mac_address: 02:42:ac:18:00:03
  redis:
    image: redis:latest
    volumes:
      - ./redis-data:/data
    networks:
      - demo
    depends_on:
      - nginx
  celery:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: celery -A tasks.tasks worker -B --loglevel=DEBUG
    volumes:
      - .:/celery_app
    networks:
      - demo
    depends_on:
      - redis

networks:
  demo:
     external: true