version: '3'

services:
  app:
    container_name: odeyalo-backend-app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
#    ports:
#    - "8080:8080"
    expose:
      - "8080"
    networks:
      - odeyalo-network
    depends_on:
      - db
    mac_address: 02:42:ac:18:00:01
  db:
    container_name: odeyalo-backend-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    networks:
      - odeyalo-network
    mac_address: 02:42:ac:18:00:02
  nginx:
    container_name: odeyalo-backend-nginx
    image: nginx:latest
#    ports:
#    - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - odeyalo-network
    depends_on:
      - app
    mac_address: 02:42:ac:18:00:03
  redis:
    container_name: odeyalo-backend-redis
    image: redis:latest
    volumes:
      - ./redis-data:/data
    networks:
      - odeyalo-network
    depends_on:
      - nginx
    mac_address: 02:42:ac:18:00:04
  celery:
    container_name: odeyalo-backend-celery
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: celery -A tasks.tasks worker -B --loglevel=DEBUG
    volumes:
      - .:/celery_app
    networks:
      - odeyalo-network
    depends_on:
      - redis
    mac_address: 02:42:ac:18:00:05

networks:
  odeyalo-network:
    name: odeyalo-network
    driver: bridge
