version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
#    ports:
#      - "8080:8080"
    expose:
      - "8080"
    networks:
      - demo
    depends_on:
      - db
    mac_address: 02:42:ac:18:00:01
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    networks:
      - demo
    mac_address: 02:42:ac:18:00:02
  nginx:
    image: nginx
#    ports:
#      - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx:ro
    networks:
      - demo
    depends_on:
      - app
    mac_address: 02:42:ac:18:00:03

networks:
  demo:
    external: true